/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupSuccessRouteImport } from './routes/signup-success'
import { Route as SaleRouteImport } from './routes/sale'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as CraftingRouteImport } from './routes/crafting'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BagRouteImport } from './routes/bag'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as CategoryCategoryRouteImport } from './routes/category.$category'
import { Route as AdminStatsRouteImport } from './routes/admin.stats'
import { Route as AdminSalesRouteImport } from './routes/admin.sales'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminItemsRouteImport } from './routes/admin.items'
import { Route as AccountSettingsRouteImport } from './routes/account.settings'
import { Route as AdminProductsIndexRouteImport } from './routes/admin.products.index'
import { Route as AdminProductsNewRouteImport } from './routes/admin.products.new'
import { Route as AdminProductsIdRouteImport } from './routes/admin.products.$id'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const SignupSuccessRoute = SignupSuccessRouteImport.update({
  id: '/signup-success',
  path: '/signup-success',
  getParentRoute: () => rootRouteImport,
} as any)
const SaleRoute = SaleRouteImport.update({
  id: '/sale',
  path: '/sale',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const CraftingRoute = CraftingRouteImport.update({
  id: '/crafting',
  path: '/crafting',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BagRoute = BagRouteImport.update({
  id: '/bag',
  path: '/bag',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategoryRoute = CategoryCategoryRouteImport.update({
  id: '/category/$category',
  path: '/category/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStatsRoute = AdminStatsRouteImport.update({
  id: '/admin/stats',
  path: '/admin/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSalesRoute = AdminSalesRouteImport.update({
  id: '/admin/sales',
  path: '/admin/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminItemsRoute = AdminItemsRouteImport.update({
  id: '/admin/items',
  path: '/admin/items',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/account/settings',
  path: '/account/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/admin/products/',
  path: '/admin/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/admin/products/new',
  path: '/admin/products/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsIdRoute = AdminProductsIdRouteImport.update({
  id: '/admin/products/$id',
  path: '/admin/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bag': typeof BagRoute
  '/contact': typeof ContactRoute
  '/crafting': typeof CraftingRoute
  '/favorites': typeof FavoritesRoute
  '/sale': typeof SaleRoute
  '/signup-success': typeof SignupSuccessRoute
  '/account/settings': typeof AccountSettingsRoute
  '/admin/items': typeof AdminItemsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/stats': typeof AdminStatsRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bag': typeof BagRoute
  '/contact': typeof ContactRoute
  '/crafting': typeof CraftingRoute
  '/favorites': typeof FavoritesRoute
  '/sale': typeof SaleRoute
  '/signup-success': typeof SignupSuccessRoute
  '/account/settings': typeof AccountSettingsRoute
  '/admin/items': typeof AdminItemsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/stats': typeof AdminStatsRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bag': typeof BagRoute
  '/contact': typeof ContactRoute
  '/crafting': typeof CraftingRoute
  '/favorites': typeof FavoritesRoute
  '/sale': typeof SaleRoute
  '/signup-success': typeof SignupSuccessRoute
  '/account/settings': typeof AccountSettingsRoute
  '/admin/items': typeof AdminItemsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/stats': typeof AdminStatsRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bag'
    | '/contact'
    | '/crafting'
    | '/favorites'
    | '/sale'
    | '/signup-success'
    | '/account/settings'
    | '/admin/items'
    | '/admin/orders'
    | '/admin/sales'
    | '/admin/stats'
    | '/category/$category'
    | '/checkout/return'
    | '/product/$id'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/admin/products/'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bag'
    | '/contact'
    | '/crafting'
    | '/favorites'
    | '/sale'
    | '/signup-success'
    | '/account/settings'
    | '/admin/items'
    | '/admin/orders'
    | '/admin/sales'
    | '/admin/stats'
    | '/category/$category'
    | '/checkout/return'
    | '/product/$id'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/admin/products'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/bag'
    | '/contact'
    | '/crafting'
    | '/favorites'
    | '/sale'
    | '/signup-success'
    | '/account/settings'
    | '/admin/items'
    | '/admin/orders'
    | '/admin/sales'
    | '/admin/stats'
    | '/category/$category'
    | '/checkout/return'
    | '/product/$id'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/admin/products/'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BagRoute: typeof BagRoute
  ContactRoute: typeof ContactRoute
  CraftingRoute: typeof CraftingRoute
  FavoritesRoute: typeof FavoritesRoute
  SaleRoute: typeof SaleRoute
  SignupSuccessRoute: typeof SignupSuccessRoute
  AccountSettingsRoute: typeof AccountSettingsRoute
  AdminItemsRoute: typeof AdminItemsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminSalesRoute: typeof AdminSalesRoute
  AdminStatsRoute: typeof AdminStatsRoute
  CategoryCategoryRoute: typeof CategoryCategoryRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ProductIdRoute: typeof ProductIdRoute
  AdminProductsIdRoute: typeof AdminProductsIdRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup-success': {
      id: '/signup-success'
      path: '/signup-success'
      fullPath: '/signup-success'
      preLoaderRoute: typeof SignupSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sale': {
      id: '/sale'
      path: '/sale'
      fullPath: '/sale'
      preLoaderRoute: typeof SaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crafting': {
      id: '/crafting'
      path: '/crafting'
      fullPath: '/crafting'
      preLoaderRoute: typeof CraftingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bag': {
      id: '/bag'
      path: '/bag'
      fullPath: '/bag'
      preLoaderRoute: typeof BagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$category': {
      id: '/category/$category'
      path: '/category/$category'
      fullPath: '/category/$category'
      preLoaderRoute: typeof CategoryCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/stats': {
      id: '/admin/stats'
      path: '/admin/stats'
      fullPath: '/admin/stats'
      preLoaderRoute: typeof AdminStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sales': {
      id: '/admin/sales'
      path: '/admin/sales'
      fullPath: '/admin/sales'
      preLoaderRoute: typeof AdminSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/items': {
      id: '/admin/items'
      path: '/admin/items'
      fullPath: '/admin/items'
      preLoaderRoute: typeof AdminItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/settings': {
      id: '/account/settings'
      path: '/account/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/admin/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/admin/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/$id': {
      id: '/admin/products/$id'
      path: '/admin/products/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AdminProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BagRoute: BagRoute,
  ContactRoute: ContactRoute,
  CraftingRoute: CraftingRoute,
  FavoritesRoute: FavoritesRoute,
  SaleRoute: SaleRoute,
  SignupSuccessRoute: SignupSuccessRoute,
  AccountSettingsRoute: AccountSettingsRoute,
  AdminItemsRoute: AdminItemsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminSalesRoute: AdminSalesRoute,
  AdminStatsRoute: AdminStatsRoute,
  CategoryCategoryRoute: CategoryCategoryRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ProductIdRoute: ProductIdRoute,
  AdminProductsIdRoute: AdminProductsIdRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
